swagger: '2.0'
info:
  description: 'Jethro Sloan Swagger store'
  version: '1.0.0'
  title: 'Swagger Store'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: 'jdksloan@gmail.com'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'petstore.swagger.io'
basePath: '/v1'
tags:
  - name: 'cart'
    description: 'Everything about the shopping cart'
schemes:
  - 'https'
paths:
  /cart:
    post:
      tags:
        - 'cart'
      summary: 'Add a new cart for the user'
      description: ''
      operationId: 'addCart'
      consumes:
        - 'application/json'
        - 'application/xml'
      produces:
        - 'application/xml'
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Cart object that needs to be added to the store'
          required: true
          schema: # Request body contents
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            example: # Sample object
              id: 10
              name: Jessica Smith
      responses:
        '405':
          description: 'Invalid input'
      security:
        - cartstore_auth:
            - 'write:carts'
            - 'read:carts'
    put:
      tags:
        - 'cart'
      summary: 'Update an existing pet'
      description: ''
      operationId: 'updatePet'
      consumes:
        - 'application/json'
        - 'application/xml'
      produces:
        - 'application/xml'
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Pet object that needs to be added to the store'
          required: true
          schema:
            $ref: '#/definitions/Cart'
      responses:
        '400':
          description: 'Invalid ID supplied'
        '404':
          description: 'Pet not found'
        '405':
          description: 'Validation exception'
      security:
        - cartstore_auth:
            - 'write:carts'
            - 'read:carts'
  /cart/{cartId}:
    get:
      tags:
        - 'cart'
      summary: 'Find pet by ID'
      description: 'Returns a single cart'
      operationId: 'getCartById'
      produces:
        - 'application/xml'
        - 'application/json'
      parameters:
        - name: 'cartId'
          in: 'path'
          description: 'ID of cart to return'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'successful operation'
          schema:
            $ref: '#/definitions/Cart'
        '400':
          description: 'Invalid ID supplied'
        '404':
          description: 'Pet not found'
      security:
        - api_key: []
securityDefinitions:
  cartstore_auth:
    type: 'oauth2'
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: 'implicit'
    scopes:
      write:carts: 'modify the cart in your account'
      read:carts: 'read the cart'
  api_key:
    type: 'apiKey'
    name: 'api_key'
    in: 'header'
definitions:
  Item:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
      price:
        type: 'integer'
      units:
        type: 'integer'
      total:
        type: 'integer'
  Cart:
    type: 'object'
    required:
      - 'name'
      - 'photoUrls'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
        example: 'doggie'
      photoUrls:
        type: 'array'
        xml:
          name: 'photoUrl'
          wrapped: true
        items:
          type: 'string'
      lineItems:
        type: 'array'
        xml:
          name: 'items'
          wrapped: true
        items:
          $ref: '#/definitions/Item'
      status:
        type: 'string'
        description: 'pet status in the store'
        enum:
          - 'available'
          - 'pending'
          - 'sold'
    xml:
      name: 'Pet'
externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'
