swagger: '2.0'
info:
  description: 'Jethro Sloan Swagger store'
  version: '1.0.0'
  title: 'Online Store'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: 'jdksloan@gmail.com'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'petstore.swagger.io'
basePath: '/v1'
tags:
  - name: 'cart'
    description: 'Everything about the shopping cart'
schemes:
  - 'https'
paths:
  /cart:
    post:
      tags:
        - 'cart'
      summary: 'Add a new cart for the user'
      description: 'Creates a new shopping cart for the user'
      operationId: 'addCart'
      consumes:
        - 'application/json'
        - 'application/xml'
      produces:
        - 'application/xml'
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Cart object that needs to be added to the store'
          required: true
          schema: # Request body contents
            $ref: '#/definitions/Cart'
      responses:
        200:
          description: 'Cart created'
        500:
          description: 'Internal error'
        405:
          description: 'Invalid input'
      security:
        - cartstore_auth:
            - 'write:carts'
            - 'read:carts'
  /cart/{userId}:
    get:
      tags:
        - 'cart'
      summary: 'Find cart by userId'
      description: 'Returns a single cart'
      operationId: 'getCartById'
      produces:
        - 'application/xml'
        - 'application/json'
      parameters:
        - name: 'userId'
          in: 'path'
          description: 'ID of user to return the cart'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'Cart found'
          schema:
            $ref: '#/definitions/Cart'
        '400':
          description: 'Invalid ID supplied'
        '404':
          description: 'Cart not found'
      security:
        - api_key: []
  /cart/item:
    put:
      tags:
        - 'cart'
      summary: 'Update a cart item'
      description: ''
      operationId: 'updateCartItem'
      consumes:
        - 'application/json'
        - 'application/xml'
      produces:
        - 'application/xml'
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Item data to be updated'
          required: true
          schema:
            $ref: '#/definitions/updateItem'
      responses:
        '400':
          description: 'Invalid ID supplied'
        '404':
          description: 'Item not found'
        '405':
          description: 'Validation exception'
      security:
        - cartstore_auth:
            - 'write:carts'
            - 'read:carts'

securityDefinitions:
  cartstore_auth:
    type: 'oauth2'
    authorizationUrl: 'http://swaggerstore.swagger.io/oauth/dialog'
    flow: 'implicit'
    scopes:
      write:carts: 'modify the cart in your account'
      read:carts: 'read the cart'
  api_key:
    type: 'apiKey'
    name: 'api_key'
    in: 'header'
definitions:
  Item:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
      price:
        type: 'integer'
      units:
        type: 'integer'
      total:
        type: 'integer'
  Cart:
    type: 'object'
    required:
      - 'lineItems'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      lineItems:
        type: 'array'
        xml:
          name: 'items'
          wrapped: true
        items:
          $ref: '#/definitions/Item'
  updateItem:
    type: 'object'
    required:
      - 'cartId'
      - 'itemId'
      - 'units'
    properties:
      cartId:
        type: 'integer'
        format: 'int64'
      itemId:
        type: 'integer'
        format: 'int64'
      units:
        type: 'integer'
        format: 'int64'
externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'
